package defpackage;

import androidx.compose.runtime.MutableState;
import com.dh.myembyapp.data.preferences.UserPreferences;
import kotlin.Unit;
import kotlin.jvm.functions.Function13;

/* JADX INFO: loaded from: classes4.dex */
public final /* synthetic */ class e4 implements Function13 {
    public final /* synthetic */ int a;
    public final /* synthetic */ UserPreferences b;
    public final /* synthetic */ MutableState c;
    public final /* synthetic */ MutableState d;
    public final /* synthetic */ MutableState e;
    public final /* synthetic */ MutableState g;
    public final /* synthetic */ MutableState h;
    public final /* synthetic */ MutableState i;
    public final /* synthetic */ MutableState j;
    public final /* synthetic */ MutableState k;
    public final /* synthetic */ MutableState l;
    public final /* synthetic */ MutableState m;
    public final /* synthetic */ MutableState n;
    public final /* synthetic */ MutableState o;
    public final /* synthetic */ MutableState p;
    public final /* synthetic */ MutableState q;
    public final /* synthetic */ MutableState r;

    public /* synthetic */ e4(UserPreferences userPreferences, MutableState mutableState, MutableState mutableState2, MutableState mutableState3, MutableState mutableState4, MutableState mutableState5, MutableState mutableState6, MutableState mutableState7, MutableState mutableState8, MutableState mutableState9, MutableState mutableState10, MutableState mutableState11, MutableState mutableState12, MutableState mutableState13, MutableState mutableState14, MutableState mutableState15, int i) {
        this.a = i;
        this.b = userPreferences;
        this.c = mutableState;
        this.d = mutableState2;
        this.e = mutableState3;
        this.g = mutableState4;
        this.h = mutableState5;
        this.i = mutableState6;
        this.j = mutableState7;
        this.k = mutableState8;
        this.l = mutableState9;
        this.m = mutableState10;
        this.n = mutableState11;
        this.o = mutableState12;
        this.p = mutableState13;
        this.q = mutableState14;
        this.r = mutableState15;
    }

    @Override // kotlin.jvm.functions.Function13
    public final Object invoke(Object obj, Object obj2, Object obj3, Object obj4, Object obj5, Object obj6, Object obj7, Object obj8, Object obj9, Object obj10, Object obj11, Object obj12, Object obj13) {
        int i = this.a;
        MutableState mutableState = this.r;
        MutableState mutableState2 = this.q;
        MutableState mutableState3 = this.p;
        MutableState mutableState4 = this.o;
        MutableState mutableState5 = this.n;
        MutableState mutableState6 = this.m;
        MutableState mutableState7 = this.l;
        MutableState mutableState8 = this.k;
        MutableState mutableState9 = this.j;
        MutableState mutableState10 = this.i;
        MutableState mutableState11 = this.h;
        MutableState mutableState12 = this.g;
        MutableState mutableState13 = this.e;
        MutableState mutableState14 = this.d;
        MutableState mutableState15 = this.c;
        UserPreferences userPreferences = this.b;
        switch (i) {
            case 0:
                Boolean bool = (Boolean) obj;
                boolean zBooleanValue = bool.booleanValue();
                Boolean bool2 = (Boolean) obj2;
                boolean zBooleanValue2 = bool2.booleanValue();
                Boolean bool3 = (Boolean) obj3;
                boolean zBooleanValue3 = bool3.booleanValue();
                Boolean bool4 = (Boolean) obj4;
                boolean zBooleanValue4 = bool4.booleanValue();
                Boolean bool5 = (Boolean) obj5;
                boolean zBooleanValue5 = bool5.booleanValue();
                Boolean bool6 = (Boolean) obj6;
                boolean zBooleanValue6 = bool6.booleanValue();
                Boolean bool7 = (Boolean) obj7;
                boolean zBooleanValue7 = bool7.booleanValue();
                Boolean bool8 = (Boolean) obj8;
                boolean zBooleanValue8 = bool8.booleanValue();
                Boolean bool9 = (Boolean) obj9;
                boolean zBooleanValue9 = bool9.booleanValue();
                Boolean bool10 = (Boolean) obj10;
                boolean zBooleanValue10 = bool10.booleanValue();
                Boolean bool11 = (Boolean) obj11;
                boolean zBooleanValue11 = bool11.booleanValue();
                Boolean bool12 = (Boolean) obj12;
                boolean zBooleanValue12 = bool12.booleanValue();
                Boolean bool13 = (Boolean) obj13;
                boolean zBooleanValue13 = bool13.booleanValue();
                mutableState15.setValue(bool);
                mutableState14.setValue(bool2);
                mutableState13.setValue(bool3);
                mutableState12.setValue(bool4);
                mutableState11.setValue(bool5);
                mutableState10.setValue(bool6);
                mutableState9.setValue(bool7);
                mutableState8.setValue(bool8);
                mutableState7.setValue(bool9);
                mutableState6.setValue(bool10);
                mutableState5.setValue(bool11);
                mutableState4.setValue(bool12);
                mutableState3.setValue(bool13);
                userPreferences.saveEnableAggregateSearch(zBooleanValue);
                userPreferences.saveEnableAggregateSearchInServerSearch(zBooleanValue2);
                userPreferences.saveDisableTopNavFocusRefresh(zBooleanValue3);
                userPreferences.saveEnableTransparentTopNavButtons(zBooleanValue4);
                userPreferences.saveEnableClickableLibrarySectionTitle(zBooleanValue5);
                userPreferences.saveEnableLibraryRowMoreButton(zBooleanValue6);
                userPreferences.saveEnableHomeUnplayedOnly(zBooleanValue7);
                userPreferences.saveEnablePlaybackStartupPoster(zBooleanValue8);
                userPreferences.saveEnableAggregateSearchVersionTags(zBooleanValue9);
                userPreferences.saveEnableDetailAggregateVersionRail(zBooleanValue10);
                userPreferences.saveEnableHomeBackFocusServerButton(zBooleanValue11);
                userPreferences.saveEnableAppUpdateCheckOnStartup(zBooleanValue12);
                userPreferences.saveEnableSpecialFeatures(zBooleanValue13);
                mutableState2.setValue(Boolean.FALSE);
                Unit unit = Unit.INSTANCE;
                mutableState.setValue(Boolean.TRUE);
                break;
            case 1:
                Boolean bool14 = (Boolean) obj;
                boolean zBooleanValue14 = bool14.booleanValue();
                Boolean bool15 = (Boolean) obj2;
                boolean zBooleanValue15 = bool15.booleanValue();
                Boolean bool16 = (Boolean) obj3;
                boolean zBooleanValue16 = bool16.booleanValue();
                Boolean bool17 = (Boolean) obj4;
                boolean zBooleanValue17 = bool17.booleanValue();
                Boolean bool18 = (Boolean) obj5;
                boolean zBooleanValue18 = bool18.booleanValue();
                Boolean bool19 = (Boolean) obj6;
                boolean zBooleanValue19 = bool19.booleanValue();
                Boolean bool20 = (Boolean) obj7;
                boolean zBooleanValue20 = bool20.booleanValue();
                Boolean bool21 = (Boolean) obj8;
                boolean zBooleanValue21 = bool21.booleanValue();
                Boolean bool22 = (Boolean) obj9;
                boolean zBooleanValue22 = bool22.booleanValue();
                Boolean bool23 = (Boolean) obj10;
                boolean zBooleanValue23 = bool23.booleanValue();
                Boolean bool24 = (Boolean) obj11;
                boolean zBooleanValue24 = bool24.booleanValue();
                Boolean bool25 = (Boolean) obj12;
                boolean zBooleanValue25 = bool25.booleanValue();
                Boolean bool26 = (Boolean) obj13;
                boolean zBooleanValue26 = bool26.booleanValue();
                mutableState15.setValue(bool14);
                mutableState14.setValue(bool15);
                mutableState13.setValue(bool16);
                mutableState12.setValue(bool17);
                mutableState11.setValue(bool18);
                mutableState10.setValue(bool19);
                mutableState9.setValue(bool20);
                mutableState8.setValue(bool21);
                mutableState7.setValue(bool22);
                mutableState6.setValue(bool23);
                mutableState5.setValue(bool24);
                mutableState4.setValue(bool25);
                mutableState3.setValue(bool26);
                userPreferences.saveEnableAggregateSearch(zBooleanValue14);
                userPreferences.saveEnableAggregateSearchInServerSearch(zBooleanValue15);
                userPreferences.saveDisableTopNavFocusRefresh(zBooleanValue16);
                userPreferences.saveEnableTransparentTopNavButtons(zBooleanValue17);
                userPreferences.saveEnableClickableLibrarySectionTitle(zBooleanValue18);
                userPreferences.saveEnableLibraryRowMoreButton(zBooleanValue19);
                userPreferences.saveEnableHomeUnplayedOnly(zBooleanValue20);
                userPreferences.saveEnablePlaybackStartupPoster(zBooleanValue21);
                userPreferences.saveEnableAggregateSearchVersionTags(zBooleanValue22);
                userPreferences.saveEnableDetailAggregateVersionRail(zBooleanValue23);
                userPreferences.saveEnableHomeBackFocusServerButton(zBooleanValue24);
                userPreferences.saveEnableAppUpdateCheckOnStartup(zBooleanValue25);
                userPreferences.saveEnableSpecialFeatures(zBooleanValue26);
                mutableState2.setValue(Boolean.FALSE);
                Unit unit2 = Unit.INSTANCE;
                mutableState.setValue(Boolean.TRUE);
                break;
            default:
                Boolean bool27 = (Boolean) obj;
                boolean zBooleanValue27 = bool27.booleanValue();
                Boolean bool28 = (Boolean) obj2;
                boolean zBooleanValue28 = bool28.booleanValue();
                Boolean bool29 = (Boolean) obj3;
                boolean zBooleanValue29 = bool29.booleanValue();
                Boolean bool30 = (Boolean) obj4;
                boolean zBooleanValue30 = bool30.booleanValue();
                Boolean bool31 = (Boolean) obj5;
                boolean zBooleanValue31 = bool31.booleanValue();
                Boolean bool32 = (Boolean) obj6;
                boolean zBooleanValue32 = bool32.booleanValue();
                Boolean bool33 = (Boolean) obj7;
                boolean zBooleanValue33 = bool33.booleanValue();
                Boolean bool34 = (Boolean) obj8;
                boolean zBooleanValue34 = bool34.booleanValue();
                Boolean bool35 = (Boolean) obj9;
                boolean zBooleanValue35 = bool35.booleanValue();
                Boolean bool36 = (Boolean) obj10;
                boolean zBooleanValue36 = bool36.booleanValue();
                Boolean bool37 = (Boolean) obj11;
                boolean zBooleanValue37 = bool37.booleanValue();
                Boolean bool38 = (Boolean) obj12;
                boolean zBooleanValue38 = bool38.booleanValue();
                Boolean bool39 = (Boolean) obj13;
                boolean zBooleanValue39 = bool39.booleanValue();
                mutableState15.setValue(bool27);
                mutableState14.setValue(bool28);
                mutableState13.setValue(bool29);
                mutableState12.setValue(bool30);
                mutableState11.setValue(bool31);
                mutableState10.setValue(bool32);
                mutableState9.setValue(bool33);
                mutableState8.setValue(bool34);
                mutableState7.setValue(bool35);
                mutableState6.setValue(bool36);
                mutableState5.setValue(bool37);
                mutableState4.setValue(bool38);
                mutableState3.setValue(bool39);
                userPreferences.saveEnableAggregateSearch(zBooleanValue27);
                userPreferences.saveEnableAggregateSearchInServerSearch(zBooleanValue28);
                userPreferences.saveDisableTopNavFocusRefresh(zBooleanValue29);
                userPreferences.saveEnableTransparentTopNavButtons(zBooleanValue30);
                userPreferences.saveEnableClickableLibrarySectionTitle(zBooleanValue31);
                userPreferences.saveEnableLibraryRowMoreButton(zBooleanValue32);
                userPreferences.saveEnableHomeUnplayedOnly(zBooleanValue33);
                userPreferences.saveEnablePlaybackStartupPoster(zBooleanValue34);
                userPreferences.saveEnableAggregateSearchVersionTags(zBooleanValue35);
                userPreferences.saveEnableDetailAggregateVersionRail(zBooleanValue36);
                userPreferences.saveEnableHomeBackFocusServerButton(zBooleanValue37);
                userPreferences.saveEnableAppUpdateCheckOnStartup(zBooleanValue38);
                userPreferences.saveEnableSpecialFeatures(zBooleanValue39);
                mutableState2.setValue(Boolean.FALSE);
                Unit unit3 = Unit.INSTANCE;
                mutableState.setValue(Boolean.TRUE);
                break;
        }
        return Unit.INSTANCE;
    }
}
