package defpackage;

import androidx.media3.exoplayer.ExoPlayer;
import com.dh.myembyapp.data.IntroOutroSettings;
import com.dh.myembyapp.data.SubtitlePreferences;
import com.dh.myembyapp.data.model.AudioVersionPrioritySettings;
import com.dh.myembyapp.data.model.DanmakuConfig;
import com.dh.myembyapp.data.model.MediaItem;
import com.dh.myembyapp.data.model.PlayerDefaultViewMode;
import com.dh.myembyapp.data.model.PlayerFrameRateMatchingMode;
import com.dh.myembyapp.data.model.PlayerResizeMode;
import com.dh.myembyapp.data.model.SubtitleVersionPrioritySettings;
import com.dh.myembyapp.data.model.SystemNetworkSpeedDisplayMode;
import com.dh.myembyapp.data.model.SystemNetworkSpeedPosition;
import com.dh.myembyapp.data.model.SystemTimeDisplayMode;
import com.dh.myembyapp.data.model.TranscodeQualityOption;
import com.dh.myembyapp.data.model.VideoVersionPrioritySettings;
import com.dh.myembyapp.data.preferences.DanmakuPreferences;
import java.util.List;
import kotlin.jvm.internal.Intrinsics;

/* JADX INFO: loaded from: classes4.dex */
public final class lg1 {
    public final String A;
    public final boolean B;
    public final boolean C;
    public final float D;
    public final int E;
    public final int F;
    public final int G;
    public final boolean H;
    public final SubtitlePreferences.SubtitleColor I;
    public final boolean J;
    public final boolean K;
    public final boolean L;
    public final boolean M;
    public final boolean N;
    public final boolean O;
    public final boolean P;
    public final boolean Q;
    public final Long R;
    public final Long S;
    public final Long T;
    public final Long U;
    public final Long V;
    public final Long W;
    public final IntroOutroSettings.Settings X;
    public final SystemNetworkSpeedDisplayMode Y;
    public final SystemNetworkSpeedPosition Z;
    public final boolean a;
    public final SystemTimeDisplayMode a0;
    public final MediaItem b;
    public final int b0;
    public final List c;
    public final int c0;
    public final String d;
    public final PlayerResizeMode d0;
    public final String e;
    public final PlayerDefaultViewMode e0;
    public final ExoPlayer f;
    public final PlayerFrameRateMatchingMode f0;
    public final long g;
    public final VideoVersionPrioritySettings g0;
    public final long h;
    public final AudioVersionPrioritySettings h0;
    public final long i;
    public final SubtitleVersionPrioritySettings i0;
    public final float j;
    public final List k;
    public final boolean l;
    public final boolean m;
    public final boolean n;
    public final TranscodeQualityOption o;
    public final Integer p;
    public final Integer q;
    public final boolean r;
    public final nv s;
    public final int t;
    public final int u;
    public final boolean v;
    public final DanmakuConfig w;
    public final DanmakuPreferences x;
    public final uw y;
    public final String z;

    public lg1(boolean z, MediaItem mediaItem, List list, String str, String str2, ExoPlayer exoPlayer, long j, long j2, long j3, float f, List list2, boolean z2, boolean z3, boolean z4, TranscodeQualityOption transcodeQualityOption, Integer num, Integer num2, boolean z5, nv nvVar, int i, int i2, boolean z6, DanmakuConfig danmakuConfig, DanmakuPreferences danmakuPreferences, uw uwVar, String str3, String str4, boolean z7, boolean z8, float f2, int i3, int i4, int i5, boolean z9, SubtitlePreferences.SubtitleColor subtitleColor, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, Long l, Long l2, Long l3, Long l4, Long l5, Long l6, IntroOutroSettings.Settings settings, SystemNetworkSpeedDisplayMode systemNetworkSpeedDisplayMode, SystemNetworkSpeedPosition systemNetworkSpeedPosition, SystemTimeDisplayMode systemTimeDisplayMode, int i6, int i7, PlayerResizeMode playerResizeMode, PlayerDefaultViewMode playerDefaultViewMode, PlayerFrameRateMatchingMode playerFrameRateMatchingMode, VideoVersionPrioritySettings videoVersionPrioritySettings, AudioVersionPrioritySettings audioVersionPrioritySettings, SubtitleVersionPrioritySettings subtitleVersionPrioritySettings) {
        mediaItem.getClass();
        exoPlayer.getClass();
        list2.getClass();
        danmakuConfig.getClass();
        uwVar.getClass();
        str3.getClass();
        subtitleColor.getClass();
        settings.getClass();
        systemNetworkSpeedDisplayMode.getClass();
        systemNetworkSpeedPosition.getClass();
        systemTimeDisplayMode.getClass();
        playerResizeMode.getClass();
        playerDefaultViewMode.getClass();
        playerFrameRateMatchingMode.getClass();
        videoVersionPrioritySettings.getClass();
        audioVersionPrioritySettings.getClass();
        subtitleVersionPrioritySettings.getClass();
        this.a = z;
        this.b = mediaItem;
        this.c = list;
        this.d = str;
        this.e = str2;
        this.f = exoPlayer;
        this.g = j;
        this.h = j2;
        this.i = j3;
        this.j = f;
        this.k = list2;
        this.l = z2;
        this.m = z3;
        this.n = z4;
        this.o = transcodeQualityOption;
        this.p = num;
        this.q = num2;
        this.r = z5;
        this.s = nvVar;
        this.t = i;
        this.u = i2;
        this.v = z6;
        this.w = danmakuConfig;
        this.x = danmakuPreferences;
        this.y = uwVar;
        this.z = str3;
        this.A = str4;
        this.B = z7;
        this.C = z8;
        this.D = f2;
        this.E = i3;
        this.F = i4;
        this.G = i5;
        this.H = z9;
        this.I = subtitleColor;
        this.J = z10;
        this.K = z11;
        this.L = z12;
        this.M = z13;
        this.N = z14;
        this.O = z15;
        this.P = z16;
        this.Q = z17;
        this.R = l;
        this.S = l2;
        this.T = l3;
        this.U = l4;
        this.V = l5;
        this.W = l6;
        this.X = settings;
        this.Y = systemNetworkSpeedDisplayMode;
        this.Z = systemNetworkSpeedPosition;
        this.a0 = systemTimeDisplayMode;
        this.b0 = i6;
        this.c0 = i7;
        this.d0 = playerResizeMode;
        this.e0 = playerDefaultViewMode;
        this.f0 = playerFrameRateMatchingMode;
        this.g0 = videoVersionPrioritySettings;
        this.h0 = audioVersionPrioritySettings;
        this.i0 = subtitleVersionPrioritySettings;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof lg1)) {
            return false;
        }
        lg1 lg1Var = (lg1) obj;
        return this.a == lg1Var.a && Intrinsics.areEqual(this.b, lg1Var.b) && Intrinsics.areEqual(this.c, lg1Var.c) && Intrinsics.areEqual(this.d, lg1Var.d) && Intrinsics.areEqual(this.e, lg1Var.e) && Intrinsics.areEqual(this.f, lg1Var.f) && this.g == lg1Var.g && this.h == lg1Var.h && this.i == lg1Var.i && Float.compare(this.j, lg1Var.j) == 0 && Intrinsics.areEqual(this.k, lg1Var.k) && this.l == lg1Var.l && this.m == lg1Var.m && this.n == lg1Var.n && Intrinsics.areEqual(this.o, lg1Var.o) && Intrinsics.areEqual(this.p, lg1Var.p) && Intrinsics.areEqual(this.q, lg1Var.q) && this.r == lg1Var.r && this.s == lg1Var.s && this.t == lg1Var.t && this.u == lg1Var.u && this.v == lg1Var.v && Intrinsics.areEqual(this.w, lg1Var.w) && Intrinsics.areEqual(this.x, lg1Var.x) && Intrinsics.areEqual(this.y, lg1Var.y) && Intrinsics.areEqual(this.z, lg1Var.z) && Intrinsics.areEqual(this.A, lg1Var.A) && this.B == lg1Var.B && this.C == lg1Var.C && Float.compare(this.D, lg1Var.D) == 0 && this.E == lg1Var.E && this.F == lg1Var.F && this.G == lg1Var.G && this.H == lg1Var.H && this.I == lg1Var.I && this.J == lg1Var.J && this.K == lg1Var.K && this.L == lg1Var.L && this.M == lg1Var.M && this.N == lg1Var.N && this.O == lg1Var.O && this.P == lg1Var.P && this.Q == lg1Var.Q && Intrinsics.areEqual(this.R, lg1Var.R) && Intrinsics.areEqual(this.S, lg1Var.S) && Intrinsics.areEqual(this.T, lg1Var.T) && Intrinsics.areEqual(this.U, lg1Var.U) && Intrinsics.areEqual(this.V, lg1Var.V) && Intrinsics.areEqual(this.W, lg1Var.W) && Intrinsics.areEqual(this.X, lg1Var.X) && this.Y == lg1Var.Y && this.Z == lg1Var.Z && this.a0 == lg1Var.a0 && this.b0 == lg1Var.b0 && this.c0 == lg1Var.c0 && this.d0 == lg1Var.d0 && this.e0 == lg1Var.e0 && this.f0 == lg1Var.f0 && Intrinsics.areEqual(this.g0, lg1Var.g0) && Intrinsics.areEqual(this.h0, lg1Var.h0) && Intrinsics.areEqual(this.i0, lg1Var.i0);
    }

    public final int hashCode() {
        int iHashCode = (this.b.hashCode() + ((this.a ? 1231 : 1237) * 31)) * 31;
        List list = this.c;
        int iHashCode2 = (iHashCode + (list == null ? 0 : list.hashCode())) * 31;
        String str = this.d;
        int iHashCode3 = (iHashCode2 + (str == null ? 0 : str.hashCode())) * 31;
        String str2 = this.e;
        int iHashCode4 = (this.f.hashCode() + ((iHashCode3 + (str2 == null ? 0 : str2.hashCode())) * 31)) * 31;
        long j = this.g;
        int i = (iHashCode4 + ((int) (j ^ (j >>> 32)))) * 31;
        long j2 = this.h;
        int i2 = (i + ((int) (j2 ^ (j2 >>> 32)))) * 31;
        long j3 = this.i;
        int iF = (((((qi0.f(this.k, qi0.e(this.j, (i2 + ((int) (j3 ^ (j3 >>> 32)))) * 31, 31), 31) + (this.l ? 1231 : 1237)) * 31) + (this.m ? 1231 : 1237)) * 31) + (this.n ? 1231 : 1237)) * 31;
        TranscodeQualityOption transcodeQualityOption = this.o;
        int iHashCode5 = (iF + (transcodeQualityOption == null ? 0 : transcodeQualityOption.hashCode())) * 31;
        Integer num = this.p;
        int iHashCode6 = (iHashCode5 + (num == null ? 0 : num.hashCode())) * 31;
        Integer num2 = this.q;
        int iHashCode7 = (((iHashCode6 + (num2 == null ? 0 : num2.hashCode())) * 31) + (this.r ? 1231 : 1237)) * 31;
        nv nvVar = this.s;
        int iHashCode8 = (((((((((((((((((((this.I.hashCode() + ((((((((qi0.e(this.D, (((i02.i(i02.i((this.y.hashCode() + ((this.x.hashCode() + ((this.w.hashCode() + ((((((((iHashCode7 + (nvVar == null ? 0 : nvVar.hashCode())) * 31) + this.t) * 31) + this.u) * 31) + (this.v ? 1231 : 1237)) * 31)) * 31)) * 31)) * 31, 31, this.z), 31, this.A) + (this.B ? 1231 : 1237)) * 31) + (this.C ? 1231 : 1237)) * 31, 31) + this.E) * 31) + this.F) * 31) + this.G) * 31) + (this.H ? 1231 : 1237)) * 31)) * 31) + (this.J ? 1231 : 1237)) * 31) + (this.K ? 1231 : 1237)) * 31) + (this.L ? 1231 : 1237)) * 31) + (this.M ? 1231 : 1237)) * 31) + (this.N ? 1231 : 1237)) * 31) + 1231) * 31) + (this.O ? 1231 : 1237)) * 31) + (this.P ? 1231 : 1237)) * 31) + (this.Q ? 1231 : 1237)) * 31;
        Long l = this.R;
        int iHashCode9 = (iHashCode8 + (l == null ? 0 : l.hashCode())) * 31;
        Long l2 = this.S;
        int iHashCode10 = (iHashCode9 + (l2 == null ? 0 : l2.hashCode())) * 31;
        Long l3 = this.T;
        int iHashCode11 = (iHashCode10 + (l3 == null ? 0 : l3.hashCode())) * 31;
        Long l4 = this.U;
        int iHashCode12 = (iHashCode11 + (l4 == null ? 0 : l4.hashCode())) * 31;
        Long l5 = this.V;
        int iHashCode13 = (iHashCode12 + (l5 == null ? 0 : l5.hashCode())) * 31;
        Long l6 = this.W;
        return this.i0.hashCode() + ((this.h0.hashCode() + ((this.g0.hashCode() + ((this.f0.hashCode() + ((this.e0.hashCode() + ((this.d0.hashCode() + ((((((this.a0.hashCode() + ((this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + ((iHashCode13 + (l6 != null ? l6.hashCode() : 0)) * 31)) * 31)) * 31)) * 31)) * 31) + this.b0) * 31) + this.c0) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("PlayerControlsOverlayState(showControlMenu=");
        sb.append(this.a);
        sb.append(", mediaItem=");
        sb.append(this.b);
        sb.append(", playbackMediaSources=");
        sb.append(this.c);
        sb.append(", titleLogoUrl=");
        sb.append(this.d);
        sb.append(", currentMediaSourceId=");
        sb.append(this.e);
        sb.append(", exoPlayer=");
        sb.append(this.f);
        sb.append(", currentPosition=");
        sb.append(this.g);
        id.m(sb, ", bufferedPosition=", this.h, ", duration=");
        sb.append(this.i);
        sb.append(", playbackSpeed=");
        sb.append(this.j);
        sb.append(", allEpisodes=");
        sb.append(this.k);
        sb.append(", enableNextEpisode=");
        sb.append(this.l);
        sb.append(", canTranscode=");
        sb.append(this.m);
        sb.append(", isTranscoding=");
        sb.append(this.n);
        sb.append(", currentTranscodeQuality=");
        sb.append(this.o);
        sb.append(", currentTranscodeAudioStreamIndex=");
        sb.append(this.p);
        sb.append(", currentTranscodeSubtitleStreamIndex=");
        sb.append(this.q);
        sb.append(", showProgressKnob=");
        sb.append(this.r);
        sb.append(", focusTarget=");
        sb.append(this.s);
        sb.append(", subtitleMenuRestoreToken=");
        sb.append(this.t);
        sb.append(", danmakuMenuRestoreToken=");
        sb.append(this.u);
        sb.append(", isDanmakuVisible=");
        sb.append(this.v);
        sb.append(", danmakuConfig=");
        sb.append(this.w);
        sb.append(", danmakuPreferences=");
        sb.append(this.x);
        sb.append(", danmakuLoadedInfo=");
        sb.append(this.y);
        sb.append(", currentDecoderMode=");
        sb.append(this.z);
        sb.append(", currentAudioDecoderMode=");
        sb.append(this.A);
        sb.append(", audioPassthroughPriorityEnabled=");
        sb.append(this.B);
        sb.append(", dv7CompatibilityEnabled=");
        sb.append(this.C);
        sb.append(", subtitleDelay=");
        sb.append(this.D);
        sb.append(", subtitleVerticalOffset=");
        sb.append(this.E);
        sb.append(", subtitleScale=");
        sb.append(this.F);
        sb.append(", subtitleBitmapBrightness=");
        sb.append(this.G);
        sb.append(", isBitmapSubtitleBrightnessEnabled=");
        sb.append(this.H);
        sb.append(", subtitleColor=");
        sb.append(this.I);
        sb.append(", isExternalSubtitle=");
        sb.append(this.J);
        sb.append(", supportsSubtitleDelay=");
        sb.append(this.K);
        sb.append(", useNativeSubtitle=");
        sb.append(this.L);
        sb.append(", isBitmapSubtitle=");
        sb.append(this.M);
        sb.append(", isSubtitlesEnabled=");
        sb.append(this.N);
        sb.append(", showAssSubtitleEnhancementToggle=true, isAssSubtitleEnhancementEnabled=");
        sb.append(this.O);
        sb.append(", isApplyingDelay=");
        sb.append(this.P);
        sb.append(", showOnlineSubtitleSearchEntry=");
        sb.append(this.Q);
        sb.append(", autoIntroStartTime=");
        sb.append(this.R);
        sb.append(", autoIntroEndTime=");
        sb.append(this.S);
        sb.append(", autoIntroTime=");
        sb.append(this.T);
        sb.append(", autoOutroTime=");
        sb.append(this.U);
        sb.append(", manualIntroTime=");
        sb.append(this.V);
        sb.append(", manualOutroRemainingMs=");
        sb.append(this.W);
        sb.append(", introOutroSettings=");
        sb.append(this.X);
        sb.append(", systemNetworkSpeedDisplayMode=");
        sb.append(this.Y);
        sb.append(", systemNetworkSpeedPosition=");
        sb.append(this.Z);
        sb.append(", systemTimeDisplayMode=");
        sb.append(this.a0);
        sb.append(", seekIntervalSec=");
        sb.append(this.b0);
        sb.append(", audioDelayMs=");
        sb.append(this.c0);
        sb.append(", playerResizeMode=");
        sb.append(this.d0);
        sb.append(", playerDefaultViewMode=");
        sb.append(this.e0);
        sb.append(", frameRateMatchingMode=");
        sb.append(this.f0);
        sb.append(", videoVersionPrioritySettings=");
        sb.append(this.g0);
        sb.append(", audioVersionPrioritySettings=");
        sb.append(this.h0);
        sb.append(", subtitleVersionPrioritySettings=");
        sb.append(this.i0);
        sb.append(")");
        return sb.toString();
    }
}
